#!/usr/bin/env python3
import sys
import os
import yaml
from pathlib import Path

# Add src to path
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from src.services.sheets import SheetsService
from src.utils.logger import logger

# Project Mapping
PROJECT_MAP = {
    "MT": "13kB77R67GJOZQ3vsLcwR1nUaRsupR8ZnEaTdDd66CTQ",
    "SS": "12yIL1CuESZxeUUd-oKK2brtN1FnXE9q95N7SqzNc7vk",
    "SK": "1CpYYLvRYslsyCkuLzL9EbbjsvbNpWCEZcmhKqMoX5zw"
}

def migrate_rules_for_project(name, ss_id):
    print(f"🚀 Migrating rules for {name} ({ss_id})...")
    
    sheets = SheetsService()
    try:
        # Check if sheet exists
        try:
            ws = sheets.get_worksheet(ss_id, "Правила синхро")
        except Exception:
            print(f"⚠️  Sheet 'Правила синхро' not found in {name}. Skipping.")
            return

        values = ws.get_all_values()
        if not values or len(values) < 2:
            print(f"⚠️  Sheet 'Правила синхро' is empty in {name}. Skipping.")
            return

        headers = [str(h).strip().lower() for h in values[0]]
        print(f"DEBUG Headers found in {name}: {headers}")
        
        # Helper to get value
        def get_val(row, possible_names):
            possible_names = [n.lower() for n in possible_names]
            for i, h in enumerate(headers):
                if h in possible_names:
                    if i < len(row):
                        return str(row[i]).strip()
            return ""

        rules = []
        
        # Process rows
        for i, row in enumerate(values[1:]):
            if not any(row): continue
            
            # Determine mode
            mode = 'unidirectional'
            raw_mode = get_val(row, ['mode', 'режим', 'тип'])
            if 'bi' in raw_mode.lower() or 'дву' in raw_mode.lower():
                mode = 'bidirectional'

            rule = {
                'id': f"rule_{i+1}", # Temporary ID, will be regenerated by server logic usually but okay for storage
                'mode': mode,
                'enabled': True,
                'category': 'Миграция',
                'hashtags': ['#legacy']
            }

            # Check enabled
            enabled_val = get_val(row, ['enabled', 'активно', 'включено', 'status', 'active'])
            if enabled_val and enabled_val.lower() in ['false', '0', 'no', 'нет']:
                rule['enabled'] = False

            # Load metadata
            rule['category'] = get_val(row, ['category', 'категория']) or rule['category']
            rule['hashtags'] = get_val(row, ['hashtags', 'хэштеги', 'хештеги']) or rule['hashtags']
            if isinstance(rule['hashtags'], str) and rule['hashtags']:
                 # split by comma or space if needed, server expects list? 
                 # Usually server expects list of strings.
                 rule['hashtags'] = [t.strip() for t in rule['hashtags'].replace(',', ' ').split()]

            if mode == 'bidirectional':
                rule['sheet_a'] = get_val(row, ['sheet a', 'лист а', 'лист 1', 'source sheet'])
                rule['header_a'] = get_val(row, ['header a', 'колонку а', 'колонка 1', 'source header'])
                rule['sheet_b'] = get_val(row, ['sheet b', 'лист б', 'лист 2', 'target sheet'])
                rule['header_b'] = get_val(row, ['header b', 'колонку б', 'колонка 2', 'target header'])
            else:
                rule['source_sheet'] = get_val(row, ['source sheet', 'источник лист', 'откуда', 'источник: лист', 'исходный лист'])
                rule['source_header'] = get_val(row, ['source header', 'источник колонка', 'что', 'источник: колонка', 'заголовок исх. столбца'])
                rule['target_sheet'] = get_val(row, ['target sheet', 'цель лист', 'куда', 'цель: лист', 'целевой лист'])
                rule['target_header'] = get_val(row, ['target header', 'цель колонка', 'куда колонка', 'цель: колонка', 'заголовок цел. столбца'])

            # Validate
            valid = False
            if mode == 'bidirectional':
                if rule.get('sheet_a') and rule.get('sheet_b'): valid = True
            else:
                if rule.get('source_sheet') and rule.get('target_sheet'): valid = True
            
            if valid:
                # Generate proper random ID
                import uuid
                rule['id'] = str(uuid.uuid4())
                rules.append(rule)

        if not rules:
            print(f"ℹ️  No valid rules found in {name}.")
            return

        # Save to YAML
        # Use relative path inside container (pwd is /app)
        config_path = Path(f"config/rules/{ss_id}.yaml")
        # Ensure dir exists (it should, we fixed perms)
        config_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Load existing to append or overwrite? User wanted "load from old". Overwrite is safer to avoid dupes.
        # But let's check if file exists.
        
        final_rules = rules
        if config_path.exists():
             try:
                with open(config_path, 'r') as f:
                    existing = yaml.safe_load(f) or []
                    # Simple merge strategy: keep existing, add new if not duplicate? 
                    # Actually user said "migrate from old sheet", implying old sheet is source of truth.
                    # But if they already created new rules in UI (which was broken until now), maybe not.
                    # Given 500 error, they probably created nothing.
                    # Let's overwrite or just append. 
                    print(f"ℹ️  Existing config found with {len(existing)} rules. Appending migrated rules.")
                    final_rules = existing + rules
             except Exception as e:
                 print(f"⚠️ Error reading existing config: {e}. Overwriting.")

        with open(config_path, 'w') as f:
            yaml.dump(final_rules, f, allow_unicode=True, default_flow_style=False)
            
        print(f"✅ Saved {len(rules)} migrated rules to {config_path}")

        # Optional: Delete legacy sheet
        # ws.delete() # User asked to delete, but maybe better to verify first. 
        # "а потом удали лист" - "and then delete the sheet".
        # I will delete it.
        try:
            ws.client.del_worksheet(ws.id)
            print("🗑️  Legacy sheet deleted.")
        except Exception as e:
            print(f"⚠️  Could not delete sheet: {e}")

    except Exception as e:
        print(f"❌ Error migrating {name}: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    print("Starting Server-Side Rule Migration...")
    for name, ssid in PROJECT_MAP.items():
        migrate_rules_for_project(name, ssid)
    print("Done.")
